learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views

#Template URLS
app_name ='basic_app'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls'),name='basic_app'),
    path('admin/', admin.site.urls),
    path('user_logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),

]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    """docstring forUserForm  ."""
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    """docstring forUserProfileInfoForm."""
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

# imports for login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',
    {
        'registered':registered,
        'user_form':user_form,
        'profile_form':profile_form
    })

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('special'))
            else:
                return HttpResponse("Accounts not active")
        else:
            print('Someone tried to login and failed!')
            print(f'User Name {username} and password {password}')
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request,'basic_app/login.html',{})

@login_required()
def special(request):
    return render(request,'basic_app/special.html',{'special_text':'Congratulations Your are logged in!'})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>

    <script type="text/javascript">
      $(document).ready(function(){
        var pathname = window.location.pathname;
        $('.nav > li > a[href="'+pathname+'"]').parent().addClass('active');
      });
    </script>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <div class="navbar-header">
            <a title="index" class="navbar-brand" href="{% url 'index' %}">Django</a>
          </div>
          <li><a title="admin" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a title="register" href="{% url 'basic_app:register' %}">Register</a></li>
          {% if user.is_authenticated %}
            <li><a title="user_logout" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a title="user_login" href="{% url 'basic_app:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
    {% block body_block %}
      <div class="jumbotron">
        <h1>Django Leevel Five</h1>
      </div>
    {% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <div class="jumbotron">
      <h1>Please Login</h1>
      <form action="{% url 'basic_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">UserName</label>
        <input type="text" name="username" placeholder="Enter a username">

        <label for="password">password</label>
        <input type="password" name="password">

        <input type="submit" name="submit" value="login">
      </form>
    </div>
  {% endblock %}

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
  {% load static %}

  {% block body_block %}
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering</h1>
      {%else%}
        <h1>Regiter Here</h1>
        <h3>Fill out the form</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{user_form.as_p}}
          {{profile_form.as_p}}
          <input type="submit" value="Register">
        </form>
      {% endif %}
    </div>
  {% endblock %}

learning_users/templates/basic_app/special.html
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <div class="jumbotron">
      <h1>{{special_text}} </h1>
    </div>
  {% endblock %}